export { default as ProfilePicture } from './ProfilePicture'
export { default as Introduction } from './Introduction'
export { default as About } from './About'
export { default as Skills } from './Skills'
export { default as Projects } from './Projects'
export { default as WorkExperience } from './WorkExperience'
export { default as Awards } from './Awards'
export { default as GetInTouch } from './GetInTouch'
